/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Device } from './Device';
import {
    DeviceFromJSON,
    DeviceFromJSONTyped,
    DeviceToJSON,
} from './Device';

/**
 * 
 * @export
 * @interface CreateDevice200Response
 */
export interface CreateDevice200Response {
    /**
     * 
     * @type {Device}
     * @memberof CreateDevice200Response
     */
    device: Device;
}

/**
 * Check if a given object implements the CreateDevice200Response interface.
 */
export function instanceOfCreateDevice200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "device" in value;

    return isInstance;
}

export function CreateDevice200ResponseFromJSON(json: any): CreateDevice200Response {
    return CreateDevice200ResponseFromJSONTyped(json, false);
}

export function CreateDevice200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateDevice200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'device': DeviceFromJSON(json['device']),
    };
}

export function CreateDevice200ResponseToJSON(value?: CreateDevice200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'device': DeviceToJSON(value.device),
    };
}

