/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeviceActivityDevice
 */
export interface DeviceActivityDevice {
    /**
     * 
     * @type {string}
     * @memberof DeviceActivityDevice
     */
    name: string;
}

/**
 * Check if a given object implements the DeviceActivityDevice interface.
 */
export function instanceOfDeviceActivityDevice(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function DeviceActivityDeviceFromJSON(json: any): DeviceActivityDevice {
    return DeviceActivityDeviceFromJSONTyped(json, false);
}

export function DeviceActivityDeviceFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeviceActivityDevice {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function DeviceActivityDeviceToJSON(value?: DeviceActivityDevice | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}

