/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Device } from './Device';
import {
    DeviceFromJSON,
    DeviceFromJSONTyped,
    DeviceToJSON,
} from './Device';

/**
 * 
 * @export
 * @interface GetDevices200Response
 */
export interface GetDevices200Response {
    /**
     * 
     * @type {Array<Device>}
     * @memberof GetDevices200Response
     */
    devices: Array<Device>;
}

/**
 * Check if a given object implements the GetDevices200Response interface.
 */
export function instanceOfGetDevices200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "devices" in value;

    return isInstance;
}

export function GetDevices200ResponseFromJSON(json: any): GetDevices200Response {
    return GetDevices200ResponseFromJSONTyped(json, false);
}

export function GetDevices200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetDevices200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'devices': ((json['devices'] as Array<any>).map(DeviceFromJSON)),
    };
}

export function GetDevices200ResponseToJSON(value?: GetDevices200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'devices': ((value.devices as Array<any>).map(DeviceToJSON)),
    };
}

