/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DeviceActivity } from './DeviceActivity';
import {
    DeviceActivityFromJSON,
    DeviceActivityFromJSONTyped,
    DeviceActivityToJSON,
} from './DeviceActivity';

/**
 * 
 * @export
 * @interface GetDeviceActivities200Response
 */
export interface GetDeviceActivities200Response {
    /**
     * 
     * @type {Array<DeviceActivity>}
     * @memberof GetDeviceActivities200Response
     */
    deviceActivities: Array<DeviceActivity>;
}

/**
 * Check if a given object implements the GetDeviceActivities200Response interface.
 */
export function instanceOfGetDeviceActivities200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "deviceActivities" in value;

    return isInstance;
}

export function GetDeviceActivities200ResponseFromJSON(json: any): GetDeviceActivities200Response {
    return GetDeviceActivities200ResponseFromJSONTyped(json, false);
}

export function GetDeviceActivities200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetDeviceActivities200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'deviceActivities': ((json['deviceActivities'] as Array<any>).map(DeviceActivityFromJSON)),
    };
}

export function GetDeviceActivities200ResponseToJSON(value?: GetDeviceActivities200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'deviceActivities': ((value.deviceActivities as Array<any>).map(DeviceActivityToJSON)),
    };
}

